version: 2.1

orbs:
  ruby: circleci/ruby@1.0

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby: [ '2.4', '2.5', '2.6', '2.7' ]
              database: [ 'mysql2', 'postgresql' ]
              sphinx_version: [ '2.2.11', '3.3.1', '2.8.2', '3.5.4' ]
              sphinx_engine: [ 'sphinx', 'manticore' ]
            exclude:
              - sphinx_version: '2.2.11'
                sphinx_engine: 'manticore'
              - sphinx_version: '3.3.1'
                sphinx_engine: 'manticore'
              - sphinx_version: '2.8.2'
                sphinx_engine: 'sphinx'
              - sphinx_version: '3.5.4'
                sphinx_engine: 'sphinx'
              - database: 'postgresql'
                sphinx_version: '3.3.1'
                sphinx_engine: 'sphinx'

jobs:
  test:
    parameters:
      ruby:
        type: string
      database:
        type: string
      sphinx_version:
        type: string
      sphinx_engine:
        type: string

    docker:
      - image: circleci/ruby:<< parameters.ruby >>
        environment:

      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: thinking_sphinx
          POSTGRES_DB: thinking_sphinx

      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: thinking_sphinx
          MYSQL_DATABASE: thinking_sphinx

    working_directory: ~/app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-<< parameters.ruby >>-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v '1.17.3'
            bundle _1.17.3_ install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: set up sphinx
          command: "./bin/loadsphinx << parameters.sphinx_version >> << parameters.sphinx_engine >>"

      - run:
          name: set up appraisal
          command: bundle _1.17.3_ exec appraisal install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-<< parameters.ruby >>-{{ checksum "Gemfile.lock" }}

      - run:
          name: tests
          environment:
            CI: "true"
            DATABASE: << parameters.database >>
            SPHINX_VERSION: << parameters.sphinx_version >>
            SPHINX_ENGINE: << parameters.sphinx_engine >>
          command: bundle _1.17.3_ exec appraisal rspec
